# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "php-discount-functions-app"
client_id = "2ae104f818472e71aa8da7e07360e883"
application_url = "https://cruises-restaurants-obesity-flag.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://cruises-restaurants-obesity-flag.trycloudflare.com/auth/callback",
  "https://cruises-restaurants-obesity-flag.trycloudflare.com/auth/shopify/callback",
  "https://cruises-restaurants-obesity-flag.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "rockyct.myshopify.com"
